name: go2-web-control
channels:
  - conda-forge
dependencies:
  - python=3.12
  - fastapi
  - uvicorn
  - jinja2
  - netifaces
  - requests
  - pip
  - pip:
    - flup
    - -e git+https://github.com/legion1581/go2_webrtc_connect.git#egg=go2_webrtc_connect
    
  