name: go2-web-control
channels:
  - conda-forge
dependencies:
  - python=3.12
  - flask
  - flask-socketio
  - jinja2
  - pip
  - pip:
    - flup
    - git+https://github.com/legion1581/go2_webrtc_connect.git
  