name: go2-web-control
channels:
  - conda-forge
dependencies:
  - python=3.12
  - flask
  - flask-socketio
  - pip

post_install:
  - pip install git+https://github.com/legion1581/go2_webrtc_connect.git  # Or your preferred pip install command
  